### ISSUE TITLE
installation on MAC

### ISSUE THREAD

**Issue by coniglione** [tamasgal/rainbowalga#1]
Some question.
1)
I would like to install your code in my Mac (10.10). I downloaded the folder rainbowalga-master in my mac and from an account with the root privilege I digit 

---

cd /Desktop/rainbowalga-master/
pip install rainbowlga
-bash: pip: command not found

---

I have the Python installed
Python 2.7.6 (default, Sep  9 2014, 15:04:36) 
[GCC 4.2.1 Compatible Apple LLVM 6.0 (clang-600.0.39)] on darwin

What has not work?
2) I did not find the format of the EVENTFILE.evt to give in input to your code. Is that
 one of our MC?

3) I suppose that the detector file is /afs/in2p3.fr/throng/km3net/detectors/km3net_jul13_90m_r1494.detx. Do you confirm? 
Thank you
Rosa

**Comment by tamasgal** [comment]
Dear Rosa,

you don’t have to download the sources from the repository, you can pull them via the ‘pip’ command. This seems not be installed on your Mac, so simply install it via

  sudo easy_install pip

after that:

  sudo pip install rainbowalga

> 2) I did not find the format of the EVENTFILE.evt to give in input to your code. Is that
> one of our MC?

That’s just the usage example, use any EVT file from our MC!

> 3) I suppose that the detector file is /afs/in2p3.fr/throng/km3net/detectors/km3net_jul13_90m_r1494.detx. Do you confirm?
> 
> It depends on what EVT files you want to display… But yes, the latest MC is using that file.

Cheers,
Tom
